[package]
name = "ize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.13.0"
rustc-hash = "1.1.0"

[[example]]
name = "expr"

[[example]]
name = "demo"