//! # Semantic checker
//!
//! The semantic checker has two main jobs:
//!
//! 1st, ensure that an IZE program is semantically correct, looking for:
//!
//! - Type mismatches.
//! - Undefined symbols.
//! - Incorrect arguments.
//! - Illegal expressions.
//!
//! 2nd, generate a symbol table:
//!
//! - Specify the entity of each symbol (is it a transfer, a module, etc).
//! - Convert identifiers into Type expressions when necessary.
//! - Infere types of variables, constants, and anonymous transfers.
//!
//! It can also offer lint warning like: variable declared and never used, imported module never used, etc.
//!
//! Semchecking is the last step before code generation.

use alloc::{borrow::ToOwned, string::String};
use rustc_hash::FxHashMap;

use crate::{
    ast::{Ast, Command, CommandKind, Expression, ExpressionKind, ModelBody, Primary},
    err::IzeErr,
    pos::RangePos,
};

#[derive(Debug, Default)]
/// Symbol Table, associate each identifier in the code with metadata.
pub struct SymbolTable {
    symbols: FxHashMap<String, SymbolMetadata>,
}

impl SymbolTable {
    /// Check if identifier is present in the ST and and is a model.
    pub fn contains_model(&self, id: &str) -> bool {
        if self.symbols.contains_key(id) {
            if let SymbolKind::Model() = self.symbols[id].kind {
                true
            } else {
                false
            }
        } else {
            false
        }
    }

    /// Insert symbol in the ST.
    pub fn insert(
        &mut self,
        key: String,
        value: SymbolMetadata,
        pos: RangePos,
    ) -> Result<(), IzeErr> {
        if !self.symbols.contains_key(key.as_str()) {
            self.symbols.insert(key, value);
            Ok(())
        } else {
            Err(IzeErr::new(format!("Symbol already exist: {}", key), pos))
        }
    }
}

#[derive(Debug)]
/// Symbol metadata.
pub struct SymbolMetadata {
    /// Is imported symbol.
    pub is_imported: IsImported,
    /// Command kind that defined this symbol.
    pub kind: SymbolKind,
}

#[derive(Debug)]
/// Symbol is generated by an import, and is defined in another AST.
pub enum IsImported {
    No,
    Yes {
        /// Real symbol name, if not renamed will be the same that apears in the symbol table.
        real_sym: String,
    },
}

impl SymbolMetadata {
    /// New SymbolMetadata.
    pub fn new(is_imported: IsImported, kind: SymbolKind) -> Self {
        Self { is_imported, kind }
    }

    /// Default model.
    pub fn default_model() -> Self {
        Self {
            is_imported: IsImported::No,
            kind: SymbolKind::Model(),
        }
    }

    /// Default transfer.
    pub fn default_transfer() -> Self {
        Self {
            is_imported: IsImported::No,
            kind: SymbolKind::Transfer(),
        }
    }

    /// Default const.
    pub fn default_const() -> Self {
        Self {
            is_imported: IsImported::No,
            kind: SymbolKind::Const(),
        }
    }

    /// Default pipe.
    pub fn default_pipe() -> Self {
        Self {
            is_imported: IsImported::No,
            kind: SymbolKind::Pipe(),
        }
    }
}

#[derive(Debug)]
/// Symbol kind. TODO: add metadata to variants.
//TODO: more metadata specific to the command, or ref to command or to the imported AST that contains the symbol
pub enum SymbolKind {
    Model(),
    Transfer(),
    Const(),
    Pipe(),
}

/// Check AST validity.
pub fn check_ast(ast: &Ast) -> Result<SymbolTable, IzeErr> {
    let mut sym_tab = SymbolTable::default();

    check_imported_symbols(ast, &mut sym_tab)?;
    insert_symbols(ast, &mut sym_tab)?;

    // Check commands in the order they appear.
    for cmd in &ast.commands {
        match &cmd.kind {
            CommandKind::Model { body, .. } => check_model(body, &mut sym_tab)?,
            CommandKind::Transfer { .. } => {
                //TODO: check transfer!!
            }
            CommandKind::Pipe { .. } => {}
            CommandKind::Run(_) => {}
            _ => {}
        }
    }

    Ok(sym_tab)
}

/// Scan each command and insert an entry into the ST, checking for duplicated.
fn insert_symbols(ast: &Ast, sym_tab: &mut SymbolTable) -> Result<(), IzeErr> {
    for cmd in &ast.commands {
        match &cmd.kind {
            CommandKind::Model { ident, .. } => {
                let sym = ident.id.clone();
                sym_tab.insert(sym.clone(), SymbolMetadata::default_model(), cmd.pos)?;
            }
            CommandKind::Transfer { ident, .. } => {
                let sym = ident.id.clone();
                sym_tab.insert(sym.clone(), SymbolMetadata::default_transfer(), cmd.pos)?;
            }
            CommandKind::Pipe { ident, .. } => {
                let sym = ident.id.clone();
                sym_tab.insert(sym.clone(), SymbolMetadata::default_pipe(), cmd.pos)?;
            }
            CommandKind::Const { ident, .. } => {
                let sym = ident.id.clone();
                sym_tab.insert(sym.clone(), SymbolMetadata::default_const(), cmd.pos)?;
            }
            _ => {}
        }
    }
    Ok(())
}

/// Check imports from an AST.
/// - Check that each imported symbol actually exists in the imported AST.
/// - Insert impored symbols into the Symbol Table and check for duplicated.
fn check_imported_symbols(ast: &Ast, sym_tab: &mut SymbolTable) -> Result<(), IzeErr> {
    for ((sym, _), import_ref) in &ast.imported_symbols {
        if is_reserved_word(sym) {
            return Err(IzeErr::new(
                format!("Symbol {sym} is a reserved identifier"),
                import_ref.pos,
            ));
        }
        let import_ast = &ast.imports[import_ref.ast_index];
        // Check that imported symbol actually exists in the imported AST.
        if let Some(sym_kind) = find_symbol_in_ast(sym, import_ast) {
            let real_sym = sym.clone();
            let sym = if let Some(rename) = &import_ref.rename {
                if is_reserved_word(rename) {
                    return Err(IzeErr::new(
                        format!("Rename symbol {rename} is a reserved identifier"),
                        import_ref.pos,
                    ));
                }
                rename.clone()
            } else {
                sym.clone()
            };
            // Insert impored symbol into the Symbol Table, or return an error if it's duplicated.
            sym_tab.insert(
                sym,
                SymbolMetadata::new(IsImported::Yes { real_sym }, sym_kind),
                import_ref.pos,
            )?;
        } else {
            return Err(IzeErr::new(
                format!(
                    "Symbol {sym} not found in imported module {}",
                    import_ast.file_path
                ),
                import_ref.pos,
            ));
        }
    }
    Ok(())
}

/// Model Check.
/// - Check that referenced types actually exist.
/// - Check struct integrity: unique attribute names, unique alias names, only one "..." field.
fn check_model(body: &ModelBody, sym_tab: &mut SymbolTable) -> Result<(), IzeErr> {
    match body {
        ModelBody::Type(type_expr) => match &type_expr.kind {
            ExpressionKind::Primary(Primary::Identifier(ident)) => {
                check_type_exists(ident, None, sym_tab, type_expr.pos)?;
            }
            ExpressionKind::Type { ident, subtypes } => {
                check_type_exists(&ident.id, Some(subtypes), sym_tab, type_expr.pos)?;
            }
            _ => {
                return Err(IzeErr::new(
                    "ModelBody::Type must contain a Type expression or a Primary identifier".into(),
                    type_expr.pos,
                ));
            }
        },
        ModelBody::Struct(pairs) => {
            let mut three_dots_found = false;
            let mut field_names = FxHashMap::default();
            let mut field_aliases = FxHashMap::default();
            for pair in pairs {
                if let ExpressionKind::Pair { left, alias, right } = &pair.kind {
                    // Look for duplicated field aliases
                    if let Some(alias) = alias {
                        if field_aliases.contains_key(&alias.id) {
                            return Err(IzeErr::new("Duplicated field alias".into(), alias.pos));
                        }
                        field_aliases.insert(alias.id.clone(), ());
                    }
                    // Look for duplicated field names
                    if let ExpressionKind::Primary(Primary::Identifier(name)) = &left.kind {
                        if field_names.contains_key(name) {
                            return Err(IzeErr::new("Duplicated field name".into(), left.pos));
                        }
                        field_names.insert(name.clone(), ());
                    } else {
                        return Err(IzeErr::new(
                            "Field name must be a primary identifier".into(),
                            left.pos,
                        ));
                    }

                    match &right.kind {
                        ExpressionKind::Primary(Primary::Identifier(ident)) => {
                            // Look for duplicated '...' fields
                            if ident == "..." {
                                if three_dots_found {
                                    return Err(IzeErr::new(
                                        "Only one '...' field allowed".into(),
                                        right.pos,
                                    ));
                                }
                                three_dots_found = true;
                            }

                            check_type_exists(ident, None, sym_tab, right.pos)?;
                        }
                        ExpressionKind::Type { ident, subtypes } => {
                            check_type_exists(&ident.id, Some(subtypes), sym_tab, right.pos)?;
                        }
                        _ => {
                            return Err(IzeErr::new(
                                "Pair right must contain a Type expression or a Primary identifier"
                                    .into(),
                                right.pos,
                            ));
                        }
                    }
                } else {
                    return Err(IzeErr::new(
                        "ModelBody::Struct must contain Pair expressions".into(),
                        pair.pos,
                    ));
                }
            }
        }
    }
    Ok(())
}

/// Check that a type is either a primitive type or is defined in the ST.
fn check_type_exists(
    ident: &str,
    subtypes: Option<&[Expression]>,
    sym_tab: &mut SymbolTable,
    pos: RangePos,
) -> Result<(), IzeErr> {
    // Type is either a primitive or is in the ST
    if !is_primitive_type(ident) && !sym_tab.contains_model(ident) {
        return Err(IzeErr::new(format!("Undefined type: {}", ident), pos));
    }
    if let Some(subtypes) = subtypes {
        for type_expr in subtypes {
            if let ExpressionKind::Type { ident, subtypes } = &type_expr.kind {
                check_type_exists(&ident.id, Some(subtypes), sym_tab, type_expr.pos)?;
            } else {
                return Err(IzeErr::new(
                    "Subtypes must be Type expressions".into(),
                    type_expr.pos,
                ));
            }
        }
        // Check compound types.
        match ident {
            // Map must contain two subtypes, and the first must be Str or Int.
            // NOTE: we would like to use any type as a key, but we can't use floats or anything that contains a float:
            // https://stackoverflow.com/questions/39638363/how-can-i-use-a-hashmap-with-f64-as-key-in-rust
            // In the future, we could improve it and use types without floats, but meanwhile we only allow Str and Int.
            "Map" => {
                if subtypes.len() != 2 {
                    return Err(IzeErr::new(
                        "Map must have two subtypes, key and value".into(),
                        pos,
                    ));
                }
                let key_type = &subtypes[0];
                if let ExpressionKind::Type { ident, .. } = &key_type.kind {
                    if ident.id != "Str" && ident.id != "Int" {
                        return Err(IzeErr::new(
                            "Map key must be either Str or Int".into(),
                            key_type.pos,
                        ));
                    }
                } else {
                    return Err(IzeErr::new(
                        "Subtypes must be Type expressions".into(),
                        key_type.pos,
                    ));
                }
            }
            // List only one subtype.
            "List" => {
                if subtypes.len() != 1 {
                    return Err(IzeErr::new("List must have one subtype".into(), pos));
                }
            }
            // Mux subtypes can't be duplicated.
            "Mux" => {
                let mut subtype_ids = FxHashMap::default();
                for type_expr in subtypes {
                    if let ExpressionKind::Type { ident, subtypes } = &type_expr.kind {
                        // Convert each type into a string representation we can use as a map key.
                        let subtype_repr = stringify_type(&ident.id, subtypes)?;
                        if subtype_ids.contains_key(&subtype_repr) {
                            return Err(IzeErr::new(
                                "Mux contains a duplicated subtype".into(),
                                type_expr.pos,
                            ));
                        }
                        subtype_ids.insert(subtype_repr, ());
                    } else {
                        return Err(IzeErr::new(
                            "Subtypes must be Type expressions".into(),
                            type_expr.pos,
                        ));
                    }
                }
            }
            _ => {}
        }
    }
    Ok(())
}

/// Convert type expression into string representation.
fn stringify_type(ident: &str, subtypes: &[Expression]) -> Result<String, IzeErr> {
    let mut serialized = ident.to_owned() + "[";
    for (index, subtype_expr) in subtypes.iter().enumerate() {
        if let ExpressionKind::Type {
            ident,
            subtypes: next_subtype,
        } = &subtype_expr.kind
        {
            let s = stringify_type(&ident.id, next_subtype)?;
            serialized += s.as_str();
            if index < subtypes.len() - 1 {
                serialized += ",";
            }
        } else {
            return Err(IzeErr::new(
                "Subtypes must be Type expressions".into(),
                subtype_expr.pos,
            ));
        }
    }
    serialized += "]";
    Ok(serialized)
}

fn find_symbol_in_ast(sym: &str, ast: &Ast) -> Option<SymbolKind> {
    for cmd in &ast.commands {
        match &cmd.kind {
            CommandKind::Transfer { ident, .. } => {
                if ident.id == sym {
                    return Some(SymbolKind::Transfer());
                }
            }
            CommandKind::Model { ident, .. } => {
                if ident.id == sym {
                    return Some(SymbolKind::Model());
                }
            }
            CommandKind::Pipe { ident, .. } => {
                if ident.id == sym {
                    return Some(SymbolKind::Pipe());
                }
            }
            CommandKind::Const { ident, .. } => {
                if ident.id == sym {
                    return Some(SymbolKind::Const());
                }
            }
            CommandKind::Run(_) => {}
            CommandKind::Import { .. } => panic!("Ast.commands can't contain an import"),
        }
    }
    None
}

/// Check if symbol is a primitive type.
fn is_primitive_type(sym: &str) -> bool {
    matches!(
        sym,
        "Str"
            | "Int"
            | "Float"
            | "Bool"
            | "None"
            | "Null"
            | "Any"
            | "Map"
            | "List"
            | "Mux"
            | "Traf"
            | "Tuple"
            | "..."
    )
}

/// Check if identifier is a reserved word.
fn is_reserved_word(id: &str) -> bool {
    matches!(
        id,
        "Str" | "Int" | "Float" | "Bool" | "None" | "Null" | "Any" | "init"
    )
}

/// Check import commands. It's a pre-check, before we have the AST.
/// - Check that "path" is a Dot expr and contains only Primary identifiers.
/// - Check that imports with "*" only contain that symbol and no rename.
/// - Check for duplicated imported symbols.
pub fn check_import_commands(commands: &[Command]) -> Result<(), IzeErr> {
    let mut imported_syms = FxHashMap::default();
    for cmd in commands {
        if let CommandKind::Import { path, symbols } = &cmd.kind {
            // Check path
            match &path.kind {
                ExpressionKind::Dot(expr_vec) => {
                    for expr in expr_vec {
                        if let ExpressionKind::Primary(Primary::Identifier(_)) = &expr.kind {
                            // Correct
                        } else {
                            return Err(IzeErr::new(
                                "All components of an import path must be identifiers".into(),
                                expr.pos,
                            ));
                        }
                    }
                }
                ExpressionKind::Primary(Primary::Identifier(_)) => {
                    // Correct
                }
                _ => {
                    return Err(IzeErr::new(
                        "The path of an import must be a dot expression or identifier".into(),
                        path.pos,
                    ))
                }
            }
            // Check symbols
            if symbols.is_empty() {
                return Err(IzeErr::new(
                    "Imported symbols must contain at least one element".into(),
                    cmd.pos,
                ));
            }
            if symbols.len() == 1 {
                // Make sure it's a "*", and no rename present
                let sym = &symbols[0];
                if sym.symbol.id == "*" && sym.rename.is_some() {
                    return Err(IzeErr::new(
                        "Imported '*' can't include a rename".into(),
                        cmd.pos,
                    ));
                }
                // TODO: implement importing all symbols
                if sym.symbol.id == "*" {
                    return Err(IzeErr::new(
                        "Importing '*' is not implemented yet".into(),
                        cmd.pos,
                    ));
                }
            }
            for sym in symbols {
                if symbols.len() > 1 {
                    // Make sure there's no "*" symbol here
                    if sym.symbol.id == "*" {
                        return Err(IzeErr::new("Imported '*' must be alone".into(), cmd.pos));
                    }
                }
                // Look for duplicated symbols
                let actual_sym = if let Some(rename) = &sym.rename {
                    rename
                } else {
                    &sym.symbol
                };
                if imported_syms.contains_key(&actual_sym.id) {
                    return Err(IzeErr::new(
                        format!("Duplicated imported symbol: {}", actual_sym.id),
                        actual_sym.pos,
                    ));
                }
                imported_syms.insert(actual_sym.id.clone(), ());
            }
        } else {
            return Err(IzeErr::new(
                "Commands passed to 'check_import_commands' must be imports".into(),
                cmd.pos,
            ));
        }
    }
    Ok(())
}

/*
Required checks:

GENERAL:

    - Check that there is no repeated name across models, pipes and consts.
    - Check that only transfers and models can have the same name. Not transfers and other kinds of commands.

TRANSFERS:

    - Check that transfers with the same name have different signatures.
    - Check that argument types and return type are either Type expressions or Primary identifiers.
    - Check all symbols used by the expression (need ST).
    - If transfer is expression, check that expression is correct in terms of types (need ETE).
    - If transfer is key/val, check all attributes exist in the return model and values are of the right type for the attribute (need ST).

MODELS:

    - Check there is no repeated model names.
    - Check all types are valid (either Type expr of Primary ident).
    - Check there is no repeated attribute names.
    - Check there is no repeated alias.
    - Check no more than one "..." field is present.
    - Check all types actually exist (need ST).
    - Recursive references (or we can use a Box to avoid problems).

PIPE:

    - Check there is no repeated pipe names.
    - Check that symbols exist and are the appropiate.
    - Check that input and output types of each step match.
    - Check arguments.

RUN:

    - If it's a pipe id, check that the id exists and it's a pipe.
    - If it's an inline pipe, same checks as PIPE apply.

IMPORT:

    - Check that imported entities do exist.
    - Check name clashes.

CONST:

    - Check there is no repeated const names.
    - Check that expression is a literal.

Expressions:

    Types:
        - Check that compound types are correctly formed (List, Map, Tuple, etc).
        - Make sure that Mux types with the same subtypes in different order are actually the same type.

    Chain expressions define a scope for variables. Chains can contain other chains, thhat inherit the parent scope plus adding its own.
*/

/*

- Build symbol table (ST):
    Scan de AST and add each model, transfer, pipe, and const identifier to a hashmap. Also scan transfer bodies looking for variables.
    Each entry will contain the entity type (model, transfer, pipe, const, let), and the types involved.
    - pipe, no types.
    - transfer, the signature, parameters and return types.
    - const, the literal type.
    - let, the type is not explicit, we have to calculate it from the expression used to define the variable. We need an Expression Type Evaluator (ETE).
*/
//- Expression Type Evaluator (ETE), given an expression, calculate the resulting type. It requires a ST already filled with explicit type symbols.
//- Use the ETE to fill the ST with non-explicit type symbols (lets).
